Fixed submodules.

diff --git a/config/zsh/zshenv b/config/zsh/zshenv
--- a/config/zsh/zshenv
+++ b/config/zsh/zshenv
@@ -1,5 +1,78 @@
 # Zsh environment variables
 
+# Home directory clean up
+# XDG Variables
+export XDG_DATA_HOME="$HOME/.local/bin/"
+export XDG_CONFIG_HOME="$HOME/.config/"
+export XDG_STATE_HOME="$HOME/.local/state/"
+export XDG_CACHE_HOME="$HOME/.cache/"
+
+export ANDROID_HOME="$XDG_DATA_HOME/android"
+
+export CARGO_HOME="$XDG_DATA_HOME/cargo"
+
+# export GNUPGHOME="$XDG_DATA_HOME"/gnupg
+
+export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
+
+# export _JAVA_OPTIONS=-Djava.io.tmpdir="$XDG_CONFIG_HOME"/java
+# export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_RUNTIME_DIR/java"
+
+export MINIKUBE_HOME="$XDG_DATA_HOME/minikube"
+
+export MPLAYER_HOME="$XDG_CONFIG_HOME/mplayer"
+
+export prefix=${XDG_DATA_HOME}/npm
+export cache=${XDG_CACHE_HOME}/npm
+export tmp=${XDG_RUNTIME_DIR}/npm
+
+export PYTHONSTARTUP="${XDG_CONFIG_HOME}/python/pythonrc"
+
+export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
+
+# export WINEPREFIX="$HOME/wine"
+
+# export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
+
+# export CC=/usr/bin/clang
+# export CXX=/usr/bin/clang++
+
+# export SSH_AUTH_SOCK
+
+# ADDING TO THE PATH
+export PATH="$PATH:$HOME/.bin/scripts:$HOME/.local/bin:$XDG_DATA_HOME/cargo/bin:$HOME/.config/doom/bin:$HOME/.config/emacs/bin:/usr/lib/jvm/java-19-openjdk/bin"
+
+# $FILEMANAGER 
+export FILEMANAGER="lf"
+
+# $EDITOR use nvim
+export EDITOR="nvim"  
+
+# $OPENER use xdg-open
+export OPENER="xdg-open"  
+
+# $TERM Sets the terminal
+# export TERM="alacritty"  
+export TERM="kitty"  
+
+# $VISUAL uses Emacs in GUI mode
+export VISUAL="/usr/bin/emacsclient --alternate-editor='/usr/bin/emacs' --create-frame"  
+
+# $PAGER uses bat with colors enabled
+export PAGER="bat --decorations=always --color=always --paging=always"
+
+# "bat" as manpager
+export MANPAGER="sh -c 'col -bx | bat -l man -p'"
+
+# $HOSTNAME current machine hostname
+export HOSTNAME="$(/bin/hostnamectl | grep 'Static hostname: ' | awk '{print $3}')"
+
+# $DISTRO current linux distribution
+export DISTRO="$(hostnamectl | grep 'Operating System' | awk '{ print substr($0, index($0,$3)) }')"
+
+# IPv4 address.
+export IPv4="${$(ip a | grep -P '^.*(?=.*inet )(?=.*dynamic).*$' | awk '{print $2}')//\/*}"
+
 alias lsxkbmodels="sed '/^! model$/,/^ *$/!d;//d' /usr/share/X11/xkb/rules/base.lst"
 alias lsxkblayouts="sed '/^! layout$/,/^ *$/!d;//d' /usr/share/X11/xkb/rules/base.lst"
 alias lsxkbvariants="sed '/^! variant$/,/^ *$/!d;//d' /usr/share/X11/xkb/rules/base.lst"
@@ -84,6 +157,10 @@ alias autoclean='paru -Scc'
 
 alias ...='../..'
 
+alias feh='feh --no-fehbg'
+
+alias wget='wget --hsts-file="$XDG_DATA_HOME/wget-hsts"'
+
 runwin() {
   WINARCH=win64
   wine "$2"
@@ -146,7 +223,7 @@ mk() {
 }
 
 ff() {
-	dirs="$(find . | fzf --header='Jump to:')"
+  dirs="$(find . | fzf --header='Jump to:')"
   if [[ "$dirs" == "." ]]; then
     cd
   fi
@@ -171,7 +248,7 @@ flash() {
 codi() {
   local syntax="${1:-python}"
   shift
-  vim -c \
+  nvim -c \
     "let g:startify_disable_at_vimenter = 1 |\
     set bt=nofile ls=0 noru nonu nornu |\
     hi ColorColumn ctermbg=NONE |\
@@ -180,31 +257,20 @@ codi() {
     Codi $syntax" "$@"
 }
 
-# the following 6 functions are unnecessary
-:q() {
-  exit
+build() {
+  local mode="${1:-Debug}"
+
+  cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -B ./build && cmake --build ./build --config "$mode" --target all -j 6 --
 }
 
-:wq() {
-  exit
+run() {
+  build "$1"
+  if [ $? -eq 0 ]; then
+    ./build/"${$(grep -P 'set\(NAME.*' ./CMakeLists.txt | awk '{print $2}')//\)}"
+  fi
 }
 
-:wqa() {
-  exit
-}
-
-:qa() {
-  exit
-}
-
-:x() {
-  exit
-}
-
-:xa() {
-  exit
-}
-
-q() {
-  exit
+installwm() {
+  # build "Release" && sudo cmake --install build/ --prefix "/usr/local/bin"
+  cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -B ./build && sudo cmake --build ./build --config Release --target install
 }
